In [1]:
import sys
import os
import pandas as pd
import numpy as np

# Append the absolute path of the root directory of the project
notebook_path = os.getcwd()
project_root = os.path.abspath(os.path.join(notebook_path, '..', '..'))

# Add the root directory to sys.path
sys.path.append(project_root)

from src.data.preprocess import DataPreprocessor
from src.models.predict_model import ModelPredictor
from src.models.train_model import ModelTrainer
from src.config import *

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
file_path = TEST_DIR

# Read the CSV
df = pd.read_csv(file_path)
preprocessor = DataPreprocessor(file_path)
preprocessor.clean_data()
prep_path = os.path.join(PROCESSED_DATA_PATH, 'preprocess.csv')
preprocessor.df.to_csv(prep_path, index = False)
preprocessor.df

Sentiment                                      News Headline  \
0     positive  The firm has seen substantial revenue growth, ...   
1     positive  The recent partnership is expected to signific...   
2     positive  Increased international sales have propelled t...   
3     positive  The company's proactive customer engagement ha...   
4     positive  A successful product launch has already starte...   
...        ...                                                ...   
9083  negative  LONDON MarketWatch -- Share prices ended lower...   
9084   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...   
9085  negative  Operating profit fell to EUR 35.4 mn from EUR ...   
9086  negative  Net sales of the Paper segment decreased to EU...   
9087  negative  Sales in Finland decreased by 10.5 % in Januar...   

                                             clean_text  sentiment_encoded  
0     firm seen substantial revenue growth driven in...                  2  
1     recent partnership expected significantly enha...                  2  
2     increased international sale propelled company...                  2  
3     company proactive customer engagement resulted...                  2  
4     successful product launch already started show...                  2  
...                                                 ...                ...  
9083  london marketwatch share price ended lower lon...                  0  
9084  rinkuskiai beer sale fell per cent million lit...                  1  
9085  operating profit fell eur mn eur mn including ...                  0  
9086  net sale paper segment decreased eur mn second...                  0  
9087  sale finland decreased january sale outside fi...                  0  

[9088 rows x 4 columns]

In [3]:
# Split the cleaned text
X_train, X_test, Y_train, Y_test = preprocessor.split_data()

In [4]:
# Example usage:
trainer = ModelTrainer()
predictor = ModelPredictor()
bayesian_network = trainer.train_bayesian_network(X_train, Y_train)
#
test_data_path = os.path.join(EXTERNAL_DATA_PATH, "test_data.csv")
# preprocessor = DataPreprocessor(test_data_path)
# preprocessor.clean_data()
# X_test, Y_test = preprocessor.df["clean_text"], preprocessor.df["sentiment_encoded"]
# Now, use the ModelPredictor to make predictions on the test data:
predictions = predictor.predict_bayesian_network(X_test)
print("Predictions:", predictions)

  0%|          | 0/1000000 [00:00<?, ?it/s]

Predictions: [2, 2, 2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 2, 2, 0, 2, 1, 0, 1, 0, 2, 1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 2, 1, 1, 2, 1, 2, 0, 1, 1, 2, 2, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 0, 2, 0, 2, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 0, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 2, 2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 2, 1, 0, 2, 1, 1,

In [5]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Accuracy
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy)

# 2. Classification Report (precision, recall, F1-score for each class)
print("Classification Report:")
print(classification_report(Y_test, predictions))

# 3. Confusion Matrix
cm = confusion_matrix(Y_test, predictions)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.7546754675467546
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.73      0.83       600
           1       0.62      0.90      0.73       618
           2       0.83      0.63      0.72       600

    accuracy                           0.75      1818
   macro avg       0.80      0.75      0.76      1818
weighted avg       0.80      0.75      0.76      1818

Confusion Matrix:
[[437 132  31]
 [ 14 555  49]
 [  8 212 380]]
