In [1]:
import sys
import os
import pandas as pd
import numpy as np

# Append the absolute path of the root directory of the project
notebook_path = os.getcwd()
project_root = os.path.abspath(os.path.join(notebook_path, '..', '..'))

# Add the root directory to sys.path
sys.path.append(project_root)

from src.data.preprocess import DataPreprocessor
from src.models.predict_model import ModelPredictor
from src.models.train_model import ModelTrainer
from src.config import *

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
file_path = TEST_DIR

# Read the CSV
df = pd.read_csv(file_path)
preprocessor = DataPreprocessor(file_path)
preprocessor.clean_data()
prep_path = os.path.join(PROCESSED_DATA_PATH, 'preprocess.csv')
preprocessor.df.to_csv(prep_path, index = False)
preprocessor.df

Sentiment                                      News Headline  \
0      neutral  According to Gran , the company has no plans t...   
1      neutral  Technopolis plans to develop in stages an area...   
2     negative  The international electronic industry company ...   
3     positive  With the new production plant the company woul...   
4     positive  According to the company 's updated strategy f...   
...        ...                                                ...   
4841  negative  LONDON MarketWatch -- Share prices ended lower...   
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...   
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...   
4844  negative  Net sales of the Paper segment decreased to EU...   
4845  negative  Sales in Finland decreased by 10.5 % in Januar...   

                                             clean_text  sentiment_encoded  
0     according gran company plan move production ru...                  1  
1     technopolis plan develop stage area less squar...                  1  
2     international electronic industry company elco...                  0  
3     new production plant company would increase ca...                  2  
4     according company updated strategy year baswar...                  2  
...                                                 ...                ...  
4841  london marketwatch share price ended lower lon...                  0  
4842  rinkuskiai beer sale fell per cent million lit...                  1  
4843  operating profit fell eur mn eur mn including ...                  0  
4844  net sale paper segment decreased eur mn second...                  0  
4845  sale finland decreased january sale outside fi...                  0  

[4846 rows x 4 columns]

In [3]:
# Split the cleaned text
X_train, X_test, Y_train, Y_test = preprocessor.split_data()

In [4]:
# Example usage:
trainer = ModelTrainer()
bayesian_network = trainer.train_bayesian_network(X_train, Y_train)
#
# Now, use the ModelPredictor to make predictions on the test data:
predictions = ModelPredictor.predict_bayesian_network(X_test, trainer)
print("Predictions:", predictions)

  0%|          | 0/1000000 [00:00<?, ?it/s]

Predictions: [np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(1)

In [5]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Accuracy
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy)

# 2. Classification Report (precision, recall, F1-score for each class)
print("Classification Report:")
print(classification_report(Y_test, predictions))

# 3. Confusion Matrix
cm = confusion_matrix(Y_test, predictions)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.6979381443298969
Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.40      0.50       121
           1       0.70      0.94      0.80       576
           2       0.70      0.32      0.44       273

    accuracy                           0.70       970
   macro avg       0.69      0.55      0.58       970
weighted avg       0.70      0.70      0.66       970

Confusion Matrix:
[[ 49  55  17]
 [ 15 540  21]
 [ 10 175  88]]
